Update cd-build-unbound.yaml
Signed-off-by: ϺΛDИVTTΛH <96331755+madnuttah@users.noreply.github.com>

diff --git a/.github/workflows/cd-build-unbound.yaml b/.github/workflows/cd-build-unbound.yaml
--- a/.github/workflows/cd-build-unbound.yaml
+++ b/.github/workflows/cd-build-unbound.yaml
@@ -93,33 +93,33 @@ jobs:
             ${{ env.DOCKERHUB_SLUG }}:${{ needs.buildvars.outputs.UNBOUND_DOCKER_IMAGE_VERSION }}
             ${{ env.DOCKERHUB_SLUG }}:latest
 
-  tag:
-    runs-on: ubuntu-latest
-    needs: build
-    permissions:
-      contents: write
+  # tag:
+    # runs-on: ubuntu-latest
+    # needs: build
+    # permissions:
+      # contents: write
   
-    steps:
-      - name: Checkout
-        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
-        with:
-          fetch-depth: 0
-          persist-credentials: false
+    # steps:
+      # - name: Checkout
+        # uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
+        # with:
+          # fetch-depth: 0
+          # persist-credentials: false
   
-      - name: Configure Git
-        run: |
-          git config user.name "github-actions"
-          git config user.email "github-actions@github.com"
-          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
+      # - name: Configure Git
+        # run: |
+          # git config user.name "github-actions"
+          # git config user.email "github-actions@github.com"
+          # git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
   
-      - name: Create and push tag
-        env:
-          VERSION: ${{ needs.buildvars.outputs.UNBOUND_DOCKER_IMAGE_VERSION }}
-        run: |
-          if [ -z "$VERSION" ]; then
-            echo "VERSION is empty — aborting"
-            exit 1
-          fi
+      # - name: Create and push tag
+        # env:
+          # VERSION: ${{ needs.buildvars.outputs.UNBOUND_DOCKER_IMAGE_VERSION }}
+        # run: |
+          # if [ -z "$VERSION" ]; then
+            # echo "VERSION is empty — aborting"
+            # exit 1
+          # fi
   
-          git tag "v$VERSION"
-          git push origin "v$VERSION"
+          # git tag "v$VERSION"
+          # git push origin "v$VERSION"
